### ISSUE TITLE
Question: Query Params support

### ISSUE THREAD

**Issue by vago** [HenrikJoreteg/feather-route-matcher#3]
Hi, simple, nice library and nice reduxbook.com book. 

Question: does the library support urls with query parameters? e.g. https://www.starbucks.com/store-locator?map=39.635307,-101.337891,5z. I tried but it didn't seem to add `map` into `params`. However, the redux store on Starbucks seems to have it in the parsed. I assume there was some customization done there. If not supported, what do you think about supporting it?

Why Starbucks? Assumption. https://read.reduxbook.com/markdown/part1/07-selectors.html --> Starbucks --> this library :)

Thanks.

**Comment by HenrikJoreteg** [comment]
Hi @vago, thanks! :)

This route matcher is pretty much a simple pattern matcher, you can see the test cases supported here: https://github.com/HenrikJoreteg/feather-route-matcher/blob/master/test.js

You typically wouldn't show different pages based on query parameters, though. 

redux-bundler (which uses this lib) has full support for all manner of manipulation or query and hash values, too. See under creatUrlBundle here: https://reduxbundler.com/api/included-bundles.html

**Comment by HenrikJoreteg** [comment]
And you're right, Starbucks isn't running redux-bundler... I created it after my work at Starbucks to formalize some of the patterns we had used there.
